[build]
  command = "npm run build"
  publish = "dist/chambea/browser"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  ANGULAR_ENV = "production"

[context.production.environment]
  API_URL = "https://chambea-api.onrender.com"