[build]
  command = "npm run build"
  publish = "dist/chambea/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server"
  status = 200
  force = true

[build.environment]
  NODE_ENV = "production"

[context.production.environment]
  NODE_ENV = "production"